import { Course, ResourceItem, DeadlineItem, StudyBuddy, FlashcardDeck, DiscussionPost } from "./types";

export const INITIAL_COURSES: Course[] = [
  {
    id: "cs301",
    code: "CS 301",
    name: "Design & Analysis of Algorithms",
    instructor: "Prof. Sarah Jenkins",
    room: "Turing Hall 204",
    credits: 4,
    color: "from-blue-600 to-indigo-600",
    attendance: {
      attended: 23,
      total: 26,
      minRequiredPercent: 75,
    },
    syllabusProgress: 68,
    nextClass: "Tomorrow, 10:00 AM",
    driveUrl: "https://drive.google.com",
  },
  {
    id: "cs340",
    code: "CS 340",
    name: "Operating Systems & Concurrency",
    instructor: "Dr. Marcus Vance",
    room: "Computing Lab B",
    credits: 4,
    color: "from-purple-600 to-pink-600",
    attendance: {
      attended: 19,
      total: 25,
      minRequiredPercent: 75,
    },
    syllabusProgress: 55,
    nextClass: "Thursday, 2:00 PM",
    driveUrl: "https://drive.google.com",
  },
  {
    id: "math240",
    code: "MATH 240",
    name: "Linear Algebra & Matrix Theory",
    instructor: "Prof. Elena Rostov",
    room: "Euler Hall 101",
    credits: 3,
    color: "from-emerald-500 to-teal-600",
    attendance: {
      attended: 22,
      total: 24,
      minRequiredPercent: 75,
    },
    syllabusProgress: 80,
    nextClass: "Friday, 11:30 AM",
    driveUrl: "https://drive.google.com",
  },
  {
    id: "ai420",
    code: "AI 420",
    name: "Applied Machine Learning & Neural Nets",
    instructor: "Dr. Kenji Sato",
    room: "Science Center 315",
    credits: 4,
    color: "from-amber-500 to-orange-600",
    attendance: {
      attended: 18,
      total: 20,
      minRequiredPercent: 75,
    },
    syllabusProgress: 62,
    nextClass: "Wednesday, 3:30 PM",
    driveUrl: "https://drive.google.com",
  },
];

export const INITIAL_RESOURCES: ResourceItem[] = [
  {
    id: "res-1",
    courseId: "cs301",
    courseCode: "CS 301",
    title: "Dynamic Programming Master Cheatsheet (Knapsack, LCS, LIS)",
    description: "Handwritten memoization tables, state transitions, and recurrence formulas condensed into 4 pages.",
    type: "cheatsheet",
    author: "Alex Rivera",
    uploadDate: "2026-09-18",
    downloads: 142,
    upvotes: 38,
    tags: ["Algorithms", "DP", "Midterm Prep"],
    fileSize: "2.4 MB",
  },
  {
    id: "res-2",
    courseId: "cs340",
    courseCode: "CS 340",
    title: "Midterm Exam 2025 (Solved with Explanations)",
    description: "Previous year paper including semaphore deadlock solutions, virtual memory paging questions, and CPU scheduling walkthroughs.",
    type: "past_paper",
    author: "David Chen",
    uploadDate: "2026-09-12",
    downloads: 289,
    upvotes: 64,
    tags: ["Past Paper", "Deadlock", "Virtual Memory"],
    fileSize: "5.1 MB",
  },
  {
    id: "res-3",
    courseId: "math240",
    courseCode: "MATH 240",
    title: "Eigenvalues, Eigenvectors & SVD Visual Guide",
    description: "Intuitive geometric breakdown of transformations, diagonalizability tests, and orthogonal projections.",
    type: "notes",
    author: "Sophia Martinez",
    uploadDate: "2026-09-20",
    downloads: 98,
    upvotes: 27,
    tags: ["Math", "Linear Algebra", "SVD"],
    fileSize: "3.8 MB",
  },
  {
    id: "res-4",
    courseId: "ai420",
    courseCode: "AI 420",
    title: "Backpropagation & Gradient Descent Step-by-Step Derivation",
    description: "Matrix calculus derivations for multi-layer perceptrons with PyTorch verification snippets.",
    type: "notes",
    author: "Liam Patel",
    uploadDate: "2026-09-15",
    downloads: 175,
    upvotes: 49,
    tags: ["Machine Learning", "Neural Nets", "Calculus"],
    fileSize: "1.9 MB",
  },
];

export const INITIAL_DEADLINES: DeadlineItem[] = [
  {
    id: "dl-1",
    courseId: "cs301",
    courseCode: "CS 301",
    title: "Graph Algorithms Problem Set 3 (Dijkstra & Prim)",
    type: "assignment",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(), // ~1.5 days
    weightPercent: 10,
    status: "in_progress",
    priority: "high",
    notes: "Requires implementing min-heap priority queue in C++ or Python.",
  },
  {
    id: "dl-2",
    courseId: "cs340",
    courseCode: "CS 340",
    title: "Operating Systems Midterm Exam",
    type: "exam",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 96).toISOString(), // 4 days
    weightPercent: 25,
    status: "pending",
    priority: "high",
    notes: "Covers Process scheduling, Semaphores, Monitors, and Virtual Memory paging.",
  },
  {
    id: "dl-3",
    courseId: "ai420",
    courseCode: "AI 420",
    title: "CNN Image Classifier Mini-Project Submission",
    type: "project",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 168).toISOString(), // 7 days
    weightPercent: 15,
    status: "pending",
    priority: "medium",
    notes: "Submit GitHub repo link and 3-page ablation study PDF.",
  },
  {
    id: "dl-4",
    courseId: "math240",
    courseCode: "MATH 240",
    title: "Weekly Quiz 5: Orthogonality & Gram-Schmidt",
    type: "quiz",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(), // 2 days
    weightPercent: 5,
    status: "pending",
    priority: "medium",
  },
];

export const INITIAL_STUDY_BUDDIES: StudyBuddy[] = [
  {
    id: "user-1",
    name: "Jordan Lee",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=face",
    currentCourse: "CS 340",
    currentTopic: "Paging & Memory Management",
    timeStudyingMinutes: 48,
    status: "focusing",
  },
  {
    id: "user-2",
    name: "Maya Patel",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&h=120&fit=crop&crop=face",
    currentCourse: "CS 301",
    currentTopic: "Bellman-Ford Algorithm",
    timeStudyingMinutes: 72,
    status: "focusing",
  },
  {
    id: "user-3",
    name: "Samir K.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop&crop=face",
    currentCourse: "MATH 240",
    currentTopic: "Gram-Schmidt Orthonormalization",
    timeStudyingMinutes: 15,
    status: "on_break",
  },
  {
    id: "user-4",
    name: "Chloe Vance",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=face",
    currentCourse: "AI 420",
    currentTopic: "ResNet Residual Connections",
    timeStudyingMinutes: 110,
    status: "focusing",
  },
];

export const INITIAL_DECKS: FlashcardDeck[] = [
  {
    id: "deck-os",
    courseId: "cs340",
    courseCode: "CS 340",
    title: "OS Core Concepts & Concurrency",
    description: "Quick-fire review of race conditions, deadlocks, scheduling algorithms, and paging.",
    cards: [
      {
        id: "c1",
        question: "What are the four necessary Coffman conditions for a deadlock to occur?",
        answer: "1. Mutual Exclusion\n2. Hold and Wait\n3. No Preemption\n4. Circular Wait",
        topic: "Deadlocks",
        mastered: false,
      },
      {
        id: "c2",
        question: "What is the difference between a Process and a Thread?",
        answer: "A process has its own dedicated address space and system resources. A thread shares address space, code, and data with other threads in the same process, but maintains its own stack and registers.",
        topic: "Concurrency",
        mastered: false,
      },
      {
        id: "c3",
        question: "What is Belady's Anomaly?",
        answer: "The phenomenon where increasing the number of page frames results in an INCREASE in the number of page faults for certain memory access patterns (most commonly seen with FIFO replacement).",
        topic: "Virtual Memory",
        mastered: true,
      },
      {
        id: "c4",
        question: "What is the difference between Internal and External Fragmentation?",
        answer: "Internal: Allocated memory block is larger than the requested payload (wasted space inside the partition).\nExternal: Total memory space exists to satisfy a request, but it is not contiguous (scattered holes).",
        topic: "Memory Management",
        mastered: false,
      },
    ],
  },
  {
    id: "deck-algo",
    courseId: "cs301",
    courseCode: "CS 301",
    title: "Algorithms & Asymptotics",
    description: "Time complexities, graph traversal invariants, and greedy criteria.",
    cards: [
      {
        id: "c5",
        question: "What is the time complexity of Dijkstra's algorithm with a Binary Min-Heap?",
        answer: "O((V + E) log V)",
        topic: "Graphs",
        mastered: true,
      },
      {
        id: "c6",
        question: "Can Dijkstra handle negative weight edges?",
        answer: "No. Dijkstra's greedy choice property assumes adding an edge only increases path cost. Use the Bellman-Ford algorithm (O(V * E)) instead.",
        topic: "Shortest Path",
        mastered: false,
      },
      {
        id: "c7",
        question: "What is the Master Theorem condition for T(n) = 2T(n/2) + O(n)?",
        answer: "Case 2: log_b(a) = log_2(2) = 1. Since f(n) = Theta(n^1), T(n) = Theta(n log n).",
        topic: "Recurrences",
        mastered: false,
      },
    ],
  },
];

export const INITIAL_POSTS: DiscussionPost[] = [
  {
    id: "post-1",
    courseCode: "CS 340",
    author: "Jordan Lee",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=face",
    timestamp: "2 hours ago",
    title: "Anyone down for a library study sprint before the Midterm on Thursday?",
    content: "Booking Room 304 in the central library tomorrow around 4 PM. Going over past exam solutions and semaphore proofs. Bring snacks!",
    tags: ["Study Group", "Midterm Prep", "OS"],
    upvotes: 14,
    repliesCount: 6,
    isPinned: true,
  },
  {
    id: "post-2",
    courseCode: "MATH 240",
    author: "Elena Zhao",
    authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&h=120&fit=crop&crop=face",
    timestamp: "4 hours ago",
    title: "Intuition check: Why does det(A) = 0 mean columns are linearly dependent?",
    content: "Struggling with the geometric intuition during lecture. Does it mean the transformation collapses the n-dimensional volume down to a lower dimension?",
    tags: ["Question", "Linear Algebra"],
    upvotes: 9,
    repliesCount: 4,
  },
];
